### ISSUE TITLE
Offline access 

### ISSUE THREAD

**Issue by ericsomto** [trynoice/android-app#1107]
why must this app use mobile internet?

Earlier this year , it was great without using mobile internet

I could play noises without mobile internet 

All of sudden i have to use mobile internet to access the app 

Would be great if people could use this offline

**Comment by ashutoshgngwr** [comment]
Offline access is available with Noice Premium plans. Please consider supporting Noice by purchasing a premium plan.

**Comment by ericsomto** [comment]
I support noise by donating a token to them once a year 
Premium plans make no sense if they consider to be foss

**Comment by ashutoshgngwr** [comment]
> I support noise by donating a token to them once a year

Please share your open collective handle or relevant proof of donation(s). I can issue a gift card for Noice Premium of the matching value. Please note that I personally discourage donations since the launch of Noice Premium.

> Premium plans make no sense if they consider to be foss

Given the time and effort it takes to build and maintain the project, Noice switched from "free as in free beer" to "free as in freedom" philosophy. Everything is still open-source under GPLv3, and you should be able to run Noice for yourself without paying for premium. The only closed-source component is the sound library. I admit documentation for self-hosting is lacking; I just haven't had the time to get to it.
