### ISSUE TITLE
Brown noise has a slight repetitive lowering of volume

### ISSUE THREAD

**Issue by ghost** [trynoice/android-app#604]
### Description
The brown noise keeps lowering the volume in a very repetitive way, the volume is not constant.

### To Reproduce
1. Play (only) Brown noise with a loud volume or in a very silent room.

### Others
- Device: Galaxy A50
- Android Version: 11
- App Version: 0.16.0 F-Droid

**Comment by ashutoshgngwr** [comment]
I'd ask if this is still an issue in v2, but I suppose that's impossible. If someone is watching this issue and feels that it is unresolved in v2, please open a new issue.

**Comment by ErichDonGubler** [comment]
There's definitely still volume inconsistency for brown, pink, and white noise in v2. In fact, there's now a regular volume dip that wasn't present in v1 that happened every 5 seconds on my S22 Ultra. It's very jarring. :(

**Comment by ashutoshgngwr** [comment]
@ErichDonGubler thanks for reporting this. I'll fix it ASAP.

**Comment by ashutoshgngwr** [comment]
@ErichDonGubler I cannot reproduce this on my device (Mi A3 on Android 11). I think this might be related to an upstream bug, but AFAIK, it affects only a few devices running on Android 10 (see #344).

A little background: Noice takes independent sound segments (MP3 files) and stitches them together on the fly using the gapless playback feature of an upstream library. The gapless playback wouldn't work on some devices due to #344. If it affects your device, you should hear the volume dip on every sound. Can you please confirm it? The fan sound is the ideal sample to test it (other than raw noise).

**Comment by ErichDonGubler** [comment]
@ashutoshgngwr: I can confirm hearing a click between each sample of the fan sound cycle. The cycle appears to indefinitely repeat a longer sample (~25s) and a shorter sample (5s).

**Comment by ashutoshgngwr** [comment]
@ErichDonGubler That's rather bad news. It is a bizzar issue with no (sane) fix. As far as I understood from https://github.com/google/ExoPlayer/issues/8594 and https://github.com/google/ExoPlayer/issues/7994, it has something to do with media decoders present on the device.

I also faced it on my device (running on Android 10 at the time). But it was automatically resolved when my device received the Android 11 update. I'll spend some more time researching, but it is very unlikely to get fixed.

**Comment by ashutoshgngwr** [comment]
@ErichDonGubler This issue was introduced in ExoPlayer version > 2.11.8. I'll start publishing alternate APKs on GitHub releases with the downgraded ExoPlayer as a workaround.

**Comment by ashutoshgngwr** [comment]
@ErichDonGubler Publishing the alternate build doesn't seem feasible. I was under the impression that ExoPlayer followed semantic versioning, but there seem to have been drastic API changes since 2.11.8. I tried to tweak the code after adding the old dependency, but there are too many breaking changes. I'll have to maintain two separate implementations of Noice's sound engine instead of doing a simple find, replace and build. I apologise, but I don't have any resources to commit for a fix that will need active maintenance on this scale.

I also tried ExoPlayer's FFMPEG decoder extension, but it broke the gapless playback entirely.

I recommend you to keep using v1 (latest release [v1.3.3](https://github.com/trynoice/android-app/releases/tag/1.3.3)) if that works for you. :)

**Comment by ashutoshgngwr** [comment]
Hey @ErichDonGubler! The upstream issue that caused this bug was just resolved (https://github.com/google/ExoPlayer/issues/8594). I tested their resolution with Noice, and it seems to be working as expected.

I'll be creating a new release for Noice soon.

**Comment by ashutoshgngwr** [comment]
Hey @ErichDonGubler, the new release is available on Google Play and GitHub. Please let me know if it is working as expected.
